name: Build container image and publish to ghcr.io
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'

jobs:
  build-container:
    name: Build container image and publish to ghcr.io
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Buiild images and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: pkgbuild-builder:latest
          platforms: linux/amd64,linux/arm64
      
      - name: Clean useless container images
        uses: actions/delete-package-versions@v5
        with:
          package-name: pkgbuild-builder
          package-type: container
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'
