name: Build container image and publish to ghcr.io
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'

jobs:
  build-container:
    name: Build container image and publish to ghcr.io
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login
        run: docker login ghcr.io --username ${{ github.repository_owner }}  --password ${{ github.token }}

      - name: Create builder
        run: docker buildx create --name pkgbuild-builder --use

      - name: Buiild manifest and images
        run: |
          docker buildx build -t ghcr.io/${{ github.repository_owner }}/pkgbuild-builder:latest \
            --platform linux/amd64,linux/arm64 \
            --push \
            .
