on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Test build action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run action
        id: test
        uses: ./build
        with:
          directory: ./tests/build

      - name: Check result
        run: |
          test -n "${{ steps.test.outputs.packages }}"

  test-build-env:
    name: Test build action with customized env input
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run action
        id: test
        uses: ./build
        with:
          directory: ./tests/build
          env: |
            CUSTOMIZED_ENV=customized-value

      - name: Check result
        run: |
          test -n "${{ steps.test.outputs.packages }}"
          tar -x -f "${{ steps.test.outputs.pacages }}"
          grep CUSTOMIZED_ENV var/env

  test-build-repo:
    name: Test build action with customized repo input
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create dummy repo
        uses: ./update-pacman-repo
        with:
          directory: repo

      - name: Run action with customized repo
        id: test
        uses: ./build
        with:
          directory: ./tests/build
          repo: repo

      - name: Check result
        run: |
          test -n "${{ steps.test.outputs.packages }}"
