name: Fetch PGP public keys
description: Fetch PGP public keys in $validpgpkeys in PKGBUILD and export ascii content in ./keys/pgp folder

inputs:
  directory:
    description: The directory contains PKGBUILD.
    required: true

outputs:
  validpgpkeys:
    description: The space splitted fingerprints.

runs:
  using: docker
  image: docker://ghcr.io/arenekosreal/pkgbuild-builder:main
  entrypoint: "/entrypoint.sh"
  args:
    - fetch-pgp-keys
    - ${{ inputs.directory }}
